### ISSUE TITLE
Hiveos

### ISSUE THREAD

**Issue by Eujenvanino** [qubic-li/hiveos#11]
GPU 2024-04-22 01:48:54 INFO    Trainer: Accept score range [0,42] & [128,256]
GPU 2024-04-22 01:48:54 INFO    Trainer: Neuron value limit: 0x1
GPU 2024-04-22 01:48:54 INFO    Trainer: Mining Seed: 61369aa3e60768781d952548dc02f24e33a10d66f19f8d224ec0b7186bfa426f
GPU 2024-04-22 01:48:54 INFO    Trainer: 6 CUDA devices are used.
GPU 2024-04-22 01:48:58 ERROR   Looks like the trainer isn't working properly :( check your config and he requirements.
GPU 2024-04-22 01:48:59 INFO    Waiting for task (0)
GPU 2024-04-22 01:49:01 INFO    Trainer: cuda version 105.3 is starting.
GPU 2024-04-22 01:49:01 INFO    Trainer: Solution threshold: 43

does not work! asks to update Glib, but it is updated, I tried to install everything from scratch, it does not work, trainer 105.3 does not start

**Comment by Worm** [comment]
The instructions are updated, pls follow the installation instructions
