### ISSUE TITLE
amd mining not working

### ISSUE THREAD

**Issue by rjohny55** [qubic-li/hiveos#12]
Name:    qubminer
Version: 1.9.5
URL:     https://github.com/qubic-li/hiveos/releases/download/v1.9.5/qubminer-1.9.5.tar.gz

> Already installed

awk: cmd. line:1: warning: regexp escape sequence `\"' is not a known regexp operator
awk: cmd. line:1: warning: regexp escape sequence `\"' is not a known regexp operator
awk: cmd. line:1: warning: regexp escape sequence `\"' is not a known regexp operator
awk: cmd. line:1: warning: regexp escape sequence `\"' is not a known regexp operator
GPU 2024-04-24 17:28:31 INFO    Starting Client 1.9.5.0
GPU 2024-04-24 17:28:31 INFO    Check for updates
GPU 2024-04-24 17:28:33 INFO    Your Client is up to date
GPU 2024-04-24 17:28:34 INFO    AI Training Starting. Your Alias is mi50x003-gpu
GPU 2024-04-24 17:28:34 INFO    Waiting for task (0)
GPU 2024-04-24 17:29:34 ERROR   Looks like the trainer isn't working properly :( check your config and he requirements.
GPU 2024-04-24 17:29:35 ERROR   GLIBC Version must by >= 2.34
GPU 2024-04-24 17:29:35 ERROR   General error: FATAL: GLIBC Version must by >= 2.34. Trainer can't be started properly.(FATAL: GLIBC Version must by >= 2.34. Trainer can't be started properly.)
GPU 
GPU System.Exception: FATAL: GLIBC Version must by >= 2.34. Trainer can't be started properly.
GPU    at li.qubic.trainer.Trainer.CheckLocalTrainer()
GPU    at li.qubic.trainer.Trainer.Start()
GPU    at li.qubic.trainer.Trainer.CheckLocalTrainer()
GPU    at li.qubic.trainer.Trainer.Start()
GPU 2024-04-24 17:29:35 INFO    Waiting for task (0)

**Comment by rjohny55** [comment]
hiveos-0.6-225-beta@240131.img.xz

**Comment by ImSorry99** [comment]
i also have this error (even with the newest hiveos beta version)

**Comment by Worm** [comment]
The instructions are updated, pls follow the installation instructions

**Comment by rjohny55** [comment]
this work
