### ISSUE TITLE
GPU Mining Error (AMD)

### ISSUE THREAD

**Issue by ImSorry99** [qubic-li/hiveos#13]
Hello :-)

i have a issue with AMD mining with the following error message: (GLIBC Version)

<img width="1448" alt="Bildschirmfoto 2024-04-26 um 15 16 34" src="https://github.com/qubic-li/hiveos/assets/74362483/c61e90b5-3be7-4254-8cdc-9bb75335c61a">

I use `0.6-225@240423` as hiveOS Version.

AMD GPU is a "Radeon RX 580 8192 MB · XFX Samsung K4G80325FB · 113-58085SHB1-W91".

Already tried apt update, apt upgrade and self upgrade with reboot afterwards. No success. 

Maybe someone can help.

Best Regards

**Comment by ImSorry99** [comment]
What I already found:
<img width="836" alt="Bildschirmfoto 2024-04-26 um 15 25 50" src="https://github.com/qubic-li/hiveos/assets/74362483/68bceecf-fc17-449f-9377-7beedd981dfe">

This might be the issue?

**Comment by ImSorry99** [comment]
After upgrading manually to LIBC 2.35 by this Manual: https://askubuntu.com/questions/1408049/how-can-i-get-glibc-2-35-on-ubuntu-20-04

i have a new error: 

<img width="813" alt="Bildschirmfoto 2024-04-26 um 15 42 33" src="https://github.com/qubic-li/hiveos/assets/74362483/adcd171b-31ee-45f5-9967-1a9713b9a696">

**Comment by Worm** [comment]
The instructions are updated, pls follow the installation instructions
