### ISSUE TITLE
problem with hiveos, first GPU card not working

### ISSUE THREAD

**Issue by handzlo** [qubic-li/hiveos#14]
Has anyone had such a problem? QUBIC first GPU card not working. This applies to all platforms.
6 cards and the first one doesn't work. 7 cards and the first one doesn't work.  On the others algorithms all GPUs run.

![qubic](https://github.com/qubic-li/hiveos/assets/168254702/38e457f8-17d9-4bf7-951c-99bbd3b68c0d)

**Comment by Worm** [comment]
You need to check your card and video card riser
