### ISSUE TITLE
Potential problem with additional apt sources to brick HiveOS

### ISSUE THREAD

**Issue by Taifuuni** [qubic-li/hiveos#3]
Please modify the following command used for installation of glibc to remove the added source after installation has finished. If we leave this source in the apt sources and user in the future does an 'apt upgrade', it has big potential to brick HiveOS installation.

Current command:

`apt update && apt upgrade -y && echo "deb http://archive.ubuntu.com/ubuntu jammy main" >> /etc/apt/sources.list && apt update && apt install tmux -y && apt install libc6 -y`

Modified command:

`apt update && apt upgrade -y && echo "deb http://archive.ubuntu.com/ubuntu jammy main" >> /etc/apt/sources.list && apt update && apt install tmux -y && apt install libc6 -y && sed -i '/deb http:\/\/archive.ubuntu.com\/ubuntu jammy main/d' /etc/apt/sources.list && apt update`

**Comment by Worm** [comment]
Thx. Solved

**Comment by Taifuuni** [comment]
Just noticed that this Github remove backward slashes from the sed command. Please use this instead

`apt update && apt upgrade -y && echo "deb http://archive.ubuntu.com/ubuntu jammy main" >> /etc/apt/sources.list && apt update && apt install tmux -y && apt install libc6 -y && sed -i '/deb http:\/\/archive.ubuntu.com\/ubuntu jammy main/d' /etc/apt/sources.list && apt update`

**Comment by dubisoft-solutions** [comment]
in what version it is solved?

**Comment by Taifuuni** [comment]
> in what version it is solved?

5 hours ago they have updated miner accordingly so latest version available.

![image](https://github.com/qubic-li/hiveos/assets/1225532/0f94c684-b77c-404a-8eac-f18237b09b06)
