### ISSUE TITLE
It is unnecessary to force hiveos update, which will make hiveos unable to run normally. In the end, you can only re-flash the hiveos image.

### ISSUE THREAD

**Issue by zhmi814** [qubic-li/hiveos#5]
# Check ts
if ! command -v ts &> /dev/null; then
    echo "Program ts (moreutils) - not installed. Moreutils is required. Install:"
    sudo sed -i '/^deb http:\/\/archive\.ubuntu\.com\/ubuntu\ jammy\ main$/d' /etc/apt/sources.list && sudo sed -i '/^deb http:\/\/archive\.ubuntu\.com\/ubuntu\ jammy\ InRelease$/d' /etc/apt/sources.list && apt update && apt install moreutils -y
    echo "Program ts (moreutils) - has been installed."
fi

######
After using the update script, my hiveos cannot display the console normally ！！！

**Comment by Worm** [comment]
It is require to install Moreutils, but:

**If you have already added the repository:** `http://archive.ubuntu.com/ubuntu jammy`, please be cautious as conflicts may arise and **HiveOs could become corrupted**. ☝️
**If the eloword package has been installed, first execute** `/hive/sbin/hive-replace --beta --yes`, and then proceed to install 'moreutils' with `apt install moreutils`.

**Comment by zhmi814** [comment]
Okay, thank you
